### ISSUE TITLE
schedule is not a function

### ISSUE THREAD

**Issue by gilbert** [MithrilJS/mithril-node-render#105]
This error gets thrown when calling `m.redraw()`:

```
TypeError: schedule is not a function
    at Function.redraw (node_modules/mithril/api/mount-redraw.js:23:4)
    at ...
    at renderComponent (node_modules/mithril-node-render/index.js:147:27)
```

I was able to get around it by putting `m.redraw = () => {}` in a particular spot. Would it be possible for mithril-node-render to do this itself? Thanks.

**Comment by isiahmeadows** [comment]
`m.redraw` is a Mithril core API, not a `mithril-node-render` API, and Mithril has never offered any real hooks to modify that. It relies exclusively on `requestAnimationFrame`, which you'll need to polyfill.

Transferring to close with the right labels.
